# Global
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: /images/favicon.ico
snow: false
enableDark: true
index_post_type: false

# Top Menu
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/
  one: /one/
  movie: /movie/
  tools:
    submenu: true
    candifonts: /
    candidenty: /


label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-archive"></i>档案馆
  friends: <i class="fa fa-mars-double"></i>朋友们
  about: <i class="fa fa-rocket"></i>关于我
  one: <i class="fa fa-podcast"></i>ONE 图文
  movie: <i class="fa fa-film"></i>电影日历
  tools:
    submenu: <i class="fa fa-flask"></i>实验室
    candifonts: 什么都没有
    candidenty: 即将到来


# Footer
qqg_link: 
contact:
  weibo:
  mail:
  telegram:
  twitter: youmohoshi
  facebook: 
  linkedin:
  fediverse:
    instance:
    username: 
  github: vensing
  rss: atom.xml
timenotice: 本站已运行

# Post Page
posts:
  show_cc: true
  donate: false
  share: true
  comments: disqusjs

# Disqus
disqus:
  shortname: vensing-com

# DisqusJS
disqusjs:
  shortname: vensing-com
  sitename: vensing
  api: https://disqusjs-api.vensing.workers.dev/api/
  apikey: bOXtpQHaIHfxsR4VGqOUNxojF6FGpwKEst7Cj3Pxo5IEAKrriBmIoxp3eegUxSqp
  admin: Cheese
  adminlabel: 芝士

# APlayer
aplayer:
  enabled: false
  playlist: 
  order: random

# Widgets
sidebar: right
widgets:
- about
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.jpg

# Code Highlight Themes: normal | night | night eighties | night blue | night bright
highlight_theme: normal

# Fancybox
fancybox: true