# Global
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: /images/favicon.ico
snow: false
enable_dark: true
cdn: false

# Index
index:
  post_type: false

# Top Menu
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/
  one: /one/
  movie: /movie/
  tools:
    submenu: true
    # cesium-wind: https://vensing.com/cesium-wind/
    # ol-meteo: https://vensing.com/ol-meteo/


label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-archive"></i>档案馆
  friends: <i class="fa fa-mars-double"></i>朋友们
  about: <i class="fa fa-rocket"></i>关于我
  one: <i class="fa fa-podcast"></i>ONE 图文
  movie: <i class="fa fa-film"></i>电影日历
  tools:
    submenu: <i class="fa fa-flask"></i>实验室
    # cesium-wind: 风场动画
    # ol-meteo: 气象可视化


# Footer
group_link: 
contact:
  weibo:
  mail:
  telegram: chee5e
  twitter: youmuhoshi
  facebook: 
  linkedin:
  fediverse:
    instance:
    username: 
  github: vensing
  rss: atom.xml
timenotice: 本站已运行
icp: 
psr:

# Post Page
posts:
  show_cc: true
  donate: false
  share: true
  comments: disqusjs

# Disqus
disqus:
  shortname: vensing-com

# DisqusJS
disqusjs:
  shortname: vensing-com
  sitename: vensing
  api: https://disqusjs-api.vensing.workers.dev/api/
  apikey: bOXtpQHaIHfxsR4VGqOUNxojF6FGpwKEst7Cj3Pxo5IEAKrriBmIoxp3eegUxSqp
  admin: Cheese
  adminlabel: 芝士

# Valine
valine:
  app_id: 
  app_key: 
  visitor: true
  enableQQ: false

# Twikoo
twikoo:
  env_id: 

# APlayer
aplayer:
  enabled: false
  playlist: 
  order: random

# Widgets
sidebar: right
widgets:
- about
- toc
- category
- tagcloud
- posts
avatarUri: /images/avatar.jpg

# Fancybox
fancybox: true

# 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript相关的配置
# 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    picCDN: false
    createTime: "2018/09/18 15:31:36"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"

# Site verify related
site_verify:
  google: 
  baidu: 
  bing: 
